---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install basic packages needed for ansible to work well
  yum: 
    name: "{{ bootstrap_pkgs }}"
    state: present
  register: bootstrap_basic_packages

- name: Reload facts if installed basic (lsb) packages
  setup:
  when: bootstrap_basic_packages.changed
